### ISSUE TITLE
Invalid or outdated plugin assmebly

### ISSUE THREAD

**Issue by Some-Birb7190** [RestoreMonarchyPlugins/Teleportation#9]
After coping the files off of github and putting the folder it gave me in the "Plugins" folder in the Rocket folder of my server, I started the server and when it got to the Rocket commands loading, I got this error.
![image](https://user-images.githubusercontent.com/68476099/104938509-1adc7c80-59a7-11eb-805a-7e3f902d9310.png)

I don't know why it has happened.

**Comment by RestoreMonarchy** [comment]
You have to install compiled plugin on your server. You can get compiled Teleportation.dll file from releases: https://github.com/RestoreMonarchyPlugins/Teleportation/releases

**Comment by Some-Birb7190** [comment]
Okay thank you :)
